services:
  chaos-oss:
    restart: unless-stopped
    volumes:
      - '/etc/chaos-oss:/opt/openlist/data'
    ports:
      - '5244:5244'
    user: '0:0'
    environment:
      - UMASK=022
      - TZ=Asia/Shanghai
    container_name: chaos-oss
    image: 'ghcr.io/chao2hang/chaos-oss:latest'
