/**
 * Chinese labels for storage-driver config field keys.
 * The backend driver schema only exposes raw snake_case keys
 * (mount_path, root_folder_id, …) — this map gives them human labels;
 * unknown keys fall back to the raw name.
 */
export const DRIVER_FIELD_LABELS: Record<string, string> = {
  // ---- common fields (all drivers) ----
  mount_path: '挂载路径',
  order: '序号',
  remark: '备注',
  cache_expiration: '缓存过期（分钟）',
  custom_cache_policies: '自定义缓存策略',
  web_proxy: 'Web 代理',
  webdav_policy: 'WebDAV 策略',
  down_proxy_url: '下载代理地址',
  disable_proxy_sign: '禁用代理签名',
  extract_folder: '解压目录',
  disable_index: '禁用索引',
  enable_sign: '启用签名',
  order_by: '排序字段',
  order_direction: '排序方向',
  proxy_range: '代理 Range',

  // ---- widely shared driver fields ----
  root_folder_id: '根目录 ID',
  root_folder_path: '根目录路径',
  username: '用户名',
  password: '密码',
  cookie: 'Cookie',
  token: '令牌',
  access_token: 'Access Token',
  refresh_token: 'Refresh Token',
  client_id: '客户端 ID',
  client_secret: '客户端密钥',
  ClientID: '客户端 ID',
  ClientSecret: '客户端密钥',
  AccessToken: 'Access Token',
  RefreshToken: 'Refresh Token',
  device_id: '设备 ID',
  upload_thread: '上传线程数',
  UploadThread: '上传线程数',
  address: '地址',
  url: '地址',
  endpoint: '端点地址',
  region: '区域',
  bucket: '存储桶',
  access_key_id: 'Access Key ID',
  secret_access_key: 'Secret Access Key',
  access_key: 'Access Key ID',
  access_secret: 'Secret Access Key',
  secret_key: 'Secret Access Key',
  session_token: '会话令牌',
  custom_host: '自定义域名',
  vendor: '供应商',
  user_agent: 'User-Agent',
  custom_ua: '自定义 UA',
  download_user_agent: '下载 UA',
  chunk_size: '分片大小',
  page_size: '每页数量',
  limit_rate: '限速',
  sign_url_expire: '签名链接有效期（秒）',
  use_online_api: '使用在线 API',
  use_online_api_bool: '使用在线 API',
  api_url_address: 'API 地址',
  enable_direct_upload: '启用直传',
  direct_upload_host: '直传地址',
  use_video_url: '使用视频地址',
  type: '类型',
  login_type: '登录方式',
  rapid_upload: '秒传',
  disable_disk_usage: '禁用磁盘用量',
  platform: '平台',
  family_id: '家庭组 ID',
  forward_archive_requests: '转发压缩包请求',
  remove_way: '删除方式',
  share_id: '分享 ID',
  share_pwd: '分享密码',
  download_api: '下载接口',
  only_list_video_file: '仅列出视频文件',
  thumbnail: '缩略图',
  thumb_cache_folder: '缩略图缓存目录',
  thumb_concurrency: '缩略图并发数',
  video_thumb_pos: '视频缩略图位置',
  show_hidden: '显示隐藏文件',
  directory_size: '统计目录大小',
  mkdir_perm: '新建目录权限',
  recycle_bin_path: '回收站路径',
  force_path_style: '路径风格（force path style）',
  list_object_version: '列对象版本',
  remove_bucket: '路径中移除桶名',
  add_filename_to_disposition: '响应头附带文件名',
  enable_custom_host_presign: '自定义域名预签名',
  placeholder: '占位符（未配置存储的提示）',
  internal_endpoint: '内网端点地址',
  acl_type: 'ACL 类型',
  DirectLink: '直链下载',
  DirectLinkPrivateKey: '直链私钥',
  DirectLinkValidDuration: '直链有效期（分钟）',
  email: '邮箱',
  app_id: '应用 ID',
  sign_type: '签名类型',
  algorithms: '算法',
  captcha_token: '验证码 Token',
  captcha_sign: '验证码签名',
  timestamp: '时间戳',
  client_version: '客户端版本',
  package_name: '包名',
  qrcode_token: '二维码令牌',
  credit_key: 'Credit Key',
  link_method: '链接方式',
  use_transcoding_address: '使用转码地址',
}

/** Human label for a driver field key (falls back to the raw key). */
export function driverFieldLabel(key: string): string {
  return DRIVER_FIELD_LABELS[key] ?? key
}
